### ISSUE TITLE
Image size should be 256x256 on Colorization.

### ISSUE THREAD

**Issue by hiouchiy** [OVaaS/OVaaS_transmit#4]
I got the error below on Azure Functions when I ran colorization app from frontend GUI on OVaaS.
This is caused by wrong image size setting. Model server seems to expect 256x256 as input shape but preprocessing logic on azure functions reshape the size to 224x224.
It would be great if you could fix this issue as soon as possible.

Error:<_InactiveRpcError of RPC that terminated with: status = StatusCode.INVALID_ARGUMENT details = "Invalid input shape - Expected: (1,1,256,256); Actual: (1,1,224,224)" debug_error_string = "{"created":"@1610685536.193439300","description":"Error received from peer ipv4:20.48.19.148:9002","file":"src/core/lib/surface/call.cc","file_line":1061,"grpc_message":"Invalid input shape - Expected: (1,1,256,256); Actual: (1,1,224,224)","grpc_status":3}" > url:https://ovaas-backend.azurewebsites.net/api/colorization method:POST

**Comment by wumoye** [comment]
The image size has been changed on colorization.
